# Generated by Django 4.0.1 on 2022-02-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_shopcart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
